user/models.py
from application import db
import datetime

class User(db.Document):
    name = db.StringField(required = True)
    email = db.StringField(required = True, unique = True)
    password = db.StringField(required = True)
    created = db.DateTimeField(default = datetime.datetime.now)
    bio = db.StringField(max_length = 200)
    profile_iamge = db.StringField()

user/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, PasswordField, validators, ValidationError
from wtforms.fields.html5 import EmailField
from wtforms.widgets import TextArea
from flask_wtf.file import FileField, FileAllowed
from user.models import User


class BaseUserForm(FlaskForm):
    name = StringField('Your name', [validators.DataRequired(), validators.Length(min=2, max=30)])
    email = EmailField('Email Address', [validators.DataRequired(), validators.Email()])
    
class RegistrationForm(BaseUserForm):
    password = PasswordField('New Password', [
               validators.DataRequired(),
               validators.EqualTo('confirm', message = 'Password must match')
    ])
    confirm = PasswordField('Repeat Password')
    
    def validate_email(FlaskForm, field):
        if User.objects.filter(email = field.data.lower()).first():
            raise ValidationError('Email address already in use')
    
 
class EditProfileForm(BaseUserForm):
    image = FileField('Profile image',
                      validators = [FileAllowed(['jpg', 'jpeg', 'png', 'gif'], 
                                                'Only allowed .jpg .npg and .gif files')])
    bio = StringField('Bio', widget = TextArea(), validators = [validators.Length(max=200)])
    
class LoginForm(FlaskForm):
    email = EmailField('Email Address', [validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', [validators.DataRequired()])
    
    
class PasswordForm(FlaskForm):
    old_password = PasswordField('Old Password', [validators.DataRequired()])
    new_password = PasswordField('New Password', [validators.DataRequired(),
                                                  validators.EqualTo('confirm', message='Passwords mush match')])
    confirm = PasswordField('Confirm Password')

user/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
import bcrypt

from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
from user.decorators import login_required
from utilities.storage import upload_image_file

user_page = Blueprint('user_page', __name__)

@user_page.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
    
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email
                return redirect(request.args.get('next') or url_for('hello'))
                user = None
        if not user:
            error = 'Your email or password was entered incorrecly!'
    return render_template('user/login.html', form = form, error= error)
# def login():
#     user = User(name = 'Cassie', password = '123', email = 'email@gmail.com')
#     user.save() # save in the mongo db
#     return "Hello, {}! Your email address is {}.".format(user.name, user.email)
@user_page.route('/signup', methods =['GET', 'POST'])
def signup():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        
        user = User(
            name = form.name.data,
            email = form.email.data.lower(),
            password = hashed_password
        )
        user.save()
        
        return '{} signed up!'.format(form.name.data)
    return render_template('user/signup.html', form = form)

@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

@user_page.route('/edit', methods = ['GET', 'POST'])
@login_required
def edit():
    user = User.objects.filter(email = session['email']).first()
    if user:
        error = None
        message = None
        form = EditProfileForm(obj = user)
        
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email = form.email.data.lower()).first():
                    error = "Email is already in use."
                else:
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                if image_url:
                    user.profile_image = image_url
                user.save()
                message = "Profile updated"
                
        return render_template('user/edit.html', user=user, form = form, error = error, message = message)
    else:
        abort(404)
        
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                slat = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)
                
                
                
                
        
        
    
    
    

templates/_formhelpers.html
{% macro render_field(field) %}
<div class = "form-group">
    {{ field.label}}
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
        <ul class = "text-danger">
        {% for error in field.errors %}
            <li>{{ error}}</li>
        {% endfor %}
        </ul>
    {% endif %}
    
</div>
{% endmacro %}

templates/base.html
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

  <!-- Custom styles for this template -->
  <style>
    .container {
      padding-top: 100px;
    }
  </style>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <a class="navbar-brand" href="/">PartyGo</a>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav ml-auto">
          
      {% if session.email %}
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ session.email }}</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('user_page.edit') }}">Edit Profile</a>
            <a class="dropdown-item" href="{{ url_for('user_page.password') }}">Change Password</a>
          </div>
        </li>
          <li class = "nav-item">
              <a class = "nav-link" href = "{{ url_for('user_page.logout')}}">Log out</a>
          </li>
        {% else %} 
        <li class="nav-item {% if request.endpoint == 'user_page.login' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('user_page.login') }}">Log In</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'user_page.signup' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('user_page.signup') }}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
     {% block content %}{% endblock %}
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</body>

</html>

templates/user/edit.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
{% block content %}
<div class = "row">
    <div class = "col-md-6 offset-md-3">
        
        <div class = "text-center">
           {% if user.profile_image %}
           <img width="150px" height="150px" src="{{ user.profile_image }}" class="img-thumbnail rounded-circle">
           {% else %}
           <img width="150px" height="150px" scr="{{ url_for('static', filename = 'img/user.png') }}" class="img-thumbnail rounded-circle">
           {% endif %}
    
        <h3>
            Edit Profile
        </h3>
        </div>
        {% if error %}
        <div class = "alert alert-danger" role = "alert">
            {{ error }}
        </div>
        {% endif %}
        {% if message %}
        <div class = "alert alert-success" role = "alert">
            {{ message }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method = "POST" action = "{{ url_for('user_page.edit') }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name, class = "form-control") }}
            {{ render_field(form.email, class = "form-control") }}
            {{ render_field(form.image, class = "form-control") }}
            {{ render_field(form.bio, rows = "3", class = "form-control") }}
            <button type="submit" class = "btn btn-success">
                Save
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div class = "row">
    <div class = "col-md-6 offset-md-3">
        <h3>
            PartyGo Login
        </h3>
        
        {% if error %}
        <div class = "alert alert-danget">
            {{ error }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method = "POST">
            {{ form.csrf_token}}
            {{ render_field(form.email, class = "form-control", placeholder = "Enter your email") }}
            {{ render_field(form.password, class = "form-control") }}
            
             <button type = "submit" class = "btn btn-success" >
                Login  
            </button>
            
        </form>
    </div>
</div>
{% endblock %}

templates/user/password.html
{% extends "base.html" %}
{% block title%}Change Your Password{% endblock %}
{% block content%}
<div class = "row">
    <div class="col-md-6 offset-md-3">
        
        <div class="text-center">
            
            <h3>
                
                Change Your Password
            </h3>
        </div>
        {% if error %}
        <div class = "alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('user_page.password') }}">
            
            {{ form.csrf_token }}
            {{ render_field(form.old_password, class="form-control") }}
            {{ render_field(form.new_password, class = "form-control") }}
            {{ render_field(form.confirm, class="form-control") }}
            
            <button type="submit" class = "btn btn-success">
                Update Password
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/user/signup.html
{% extends "base.html" %}
{% block title %}SignUp{% endblock %}
{% block content %}
<div class = "row">
    <div class = "col-md-6 offset-md-3"> 
        <h3>
            Sign Up
        </h3>
        {% from "_formhelpers.html" import render_field %}
        <form method = "POST" action = "{{ url_for('user_page.signup') }}">
            {{ form.csrf_token }}
            {{ render_field(form.name, class = "form-control", placeholder = "Enter your name")}}
            {{ render_field(form.email, class = "form-control")}}
            {{ render_field(form.password, class = "form-control")}}
            {{ render_field(form.confirm, class = "form-control")}}
            
            <button type = "submit" class = "btn btn-success">
                Sign Up   
            </button>
        </form>
    </div>
</div>
{% endblock %}